insert into paintings (painting_id, title, year) values (1, 'Spider', 2002);
insert into paintings (painting_id, title, year) values (2, 'My Crazy Life (Mi vida loca)', 2006);
insert into paintings (painting_id, title, year) values (3, 'Escape From Tomorrow', 1993);
insert into paintings (painting_id, title, year) values (4, 'Old Joy', 1994);
insert into paintings (painting_id, title, year) values (5, 'Love Forbidden (Défense d''aimer)', 1986);
insert into paintings (painting_id, title, year) values (6, 'Attack the Gas Station! (Juyuso seubgyuksageun)', 2011);
insert into paintings (painting_id, title, year) values (7, 'Painless (Insensibles) ', 2005);
insert into paintings (painting_id, title, year) values (8, 'This Is Spinal Tap', 2006);
insert into paintings (painting_id, title, year) values (9, 'Smiling Lieutenant, The', 2003);
insert into paintings (painting_id, title, year) values (10, 'Universal Soldier: The Return', 2009);
insert into galleries (gallery_id, name, open_from, open_until, street_address, city, province, country, postal_code) values (11, 'Kanoodle', 'Wednesday', 'Sunday', '9 Moulton Avenue', 'Baoquanshan', 'Ontario', 'Indonesia', 'J4W 2W2');
insert into galleries (gallery_id, name, open_from, open_until, street_address, city, province, country, postal_code) values (12, 'Ntag', 'Thursday', 'Sunday', '86 Gateway Center', 'Kargowa', 'Quebec', 'Georgia', '66-120');
insert into galleries (gallery_id, name, open_from, open_until, street_address, city, province, country, postal_code) values (13, 'Abata', 'Tuesday', 'Saturday', '884 Nova Alley', 'Kobilje', 'Manitoba', 'Czech Republic', '9227');
insert into galleries (gallery_id, name, open_from, open_until, street_address, city, province, country, postal_code) values (14, 'Quinu', 'Monday', 'Saturday', '67 Leroy Way', 'Irbid', 'Ontario', 'Canada', 'J4W 1W6');